source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TSCustomDatePicker_Example', :exclusive => true do
  pod "TSCustomDatePicker", :path => "../"
end

target 'TSCustomDatePicker_Tests', :exclusive => true do
  pod "TSCustomDatePicker", :path => "../"

  
end
